#extension GL_ARB_compute_shader : enable
#extension GL_ARB_shader_storage_buffer_object : enable

#include veil:camera

layout(std430) buffer GrassPositions {
    vec3 Position[];
};

layout(binding = 0) uniform atomic_uint VeilLightCount;

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main() {
    uint idx = gl_GlobalInvocationID.x;
    vec3 pos = vec3(1);

    Position[idx] = pos;
}